module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert(
      'Rooms',
      [
        {
          number: '100',
          category: 'Стандартный',
          floor: '1',
          price: 100,
          isClean: true,
          comment: 'Теплая цветовая гамма, уникальная комплектация',
          isOccupied: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          number: '101',
          category: 'Стандартный',
          floor: '2',
          price: 100,
          isClean: true,
          comment: 'Самый простой и бюджетный вариант',
          isOccupied: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          number: '102',
          category: 'Стандартный',
          floor: '3',
          price: 100,
          isClean: true,
          comment: 'бюджетный вариант размещения для неприхотливых туристов',
          isOccupied: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          number: '103',
          category: 'Стандартный',
          floor: '4',
          price: 100,
          isClean: true,
          comment: 'Постельное белье и полотенца меняются каждый день',
          isOccupied: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          number: '104',
          category: 'Стандартный',
          floor: '5',
          price: 100,
          isClean: true,
          comment: 'Самый простой и бюджетный вариант',
          isOccupied: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          number: '105',
          category: 'Стандартный',
          floor: '1',
          price: 100,
          isClean: true,
          comment: 'Теплая цветовая гамма, уникальная комплектация',
          isOccupied: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          number: '106',
          category: 'Стандартный',
          floor: '2',
          price: 100,
          isClean: true,
          comment: 'Самый простой и бюджетный вариант',
          isOccupied: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          number: '107',
          category: 'Стандартный',
          floor: '3',
          price: 100,
          isClean: true,
          comment: 'бюджетный вариант размещения для неприхотливых туристов',
          isOccupied: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          number: '108',
          category: 'Стандартный',
          floor: '4',
          price: 100,
          isClean: true,
          comment: 'Постельное белье и полотенца меняются каждый день',
          isOccupied: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          number: '109',
          category: 'Стандартный',
          floor: '5',
          price: 100,
          isClean: true,
          comment: 'Самый простой и бюджетный вариант',
          isOccupied: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          number: '110',
          category: 'Стандартный',
          floor: '1',
          price: 100,
          isClean: true,
          comment: 'Теплая цветовая гамма, уникальная комплектация',
          isOccupied: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          number: '111',
          category: 'Стандартный',
          floor: '2',
          price: 100,
          isClean: true,
          comment: 'Самый простой и бюджетный вариант',
          isOccupied: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          number: '112',
          category: 'Стандартный',
          floor: '3',
          price: 100,
          isClean: true,
          comment: 'бюджетный вариант размещения для неприхотливых туристов',
          isOccupied: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          number: '113',
          category: 'Стандартный',
          floor: '4',
          price: 100,
          isClean: true,
          comment: 'Постельное белье и полотенца меняются каждый день',
          isOccupied: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          number: '115',
          category: 'Стандартный',
          floor: '5',
          price: 100,
          isClean: true,
          comment: 'Самый простой и бюджетный вариант',
          isOccupied: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          number: '200',
          category: 'Двухместный',
          floor: '1',
          price: 200,
          isClean: true,
          comment: 'обычный набор техники — телефон, телевизор, холодильник.',
          isOccupied: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          number: '201',
          category: 'Двухместный',
          floor: '2',
          price: 200,
          isClean: true,
          comment: 'Удобная двухспальная кровать, кондиционер, сейф, телевизор с плоским экраном, беспроводной интернет Wi-Fi,',
          isOccupied: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          number: '202',
          category: 'Двухместный',
          floor: '3',
          price: 200,
          isClean: true,
          comment: 'В ванной комнате: душевая зона с перегородкой из закалённого стекла. Халаты в номере',
          isOccupied: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          number: '203',
          category: 'Двухместный',
          floor: '4',
          price: 200,
          isClean: true,
          comment: 'Большая кровать, ванная комната с душевой кабиной, рабочее место(стол), звуконепроницаемые окна, WLAN интернет, телефон, телевизор с полоским экраном, DVD плеер, кондиционер, мини бар',
          isOccupied: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          number: '204',
          category: 'Двухместный',
          floor: '5',
          price: 200,
          isClean: true,
          comment: 'Прекрасный вид из окна',
          isOccupied: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          number: '205',
          category: 'Двухместный',
          floor: '1',
          price: 200,
          isClean: true,
          comment: 'обычный набор техники — телефон, телевизор, холодильник.',
          isOccupied: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          number: '206',
          category: 'Двухместный',
          floor: '2',
          price: 200,
          isClean: true,
          comment: 'Удобная двухспальная кровать, кондиционер, сейф, телевизор с плоским экраном, беспроводной интернет Wi-Fi,',
          isOccupied: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          number: '207',
          category: 'Двухместный',
          floor: '3',
          price: 200,
          isClean: true,
          comment: 'В ванной комнате: душевая зона с перегородкой из закалённого стекла. Халаты в номере',
          isOccupied: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          number: '208',
          category: 'Двухместный',
          floor: '4',
          price: 200,
          isClean: true,
          comment: 'Большая кровать, ванная комната с душевой кабиной, рабочее место(стол), звуконепроницаемые окна, WLAN интернет, телефон, телевизор с полоским экраном, DVD плеер, кондиционер, мини бар',
          isOccupied: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          number: '209',
          category: 'Двухместный',
          floor: '5',
          price: 200,
          isClean: true,
          comment: 'Прекрасный вид из окна',
          isOccupied: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          number: '210',
          category: 'Двухместный',
          floor: '1',
          price: 200,
          isClean: true,
          comment: 'обычный набор техники — телефон, телевизор, холодильник.',
          isOccupied: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          number: '211',
          category: 'Двухместный',
          floor: '2',
          price: 200,
          isClean: true,
          comment: 'Удобная двухспальная кровать, кондиционер, сейф, телевизор с плоским экраном, беспроводной интернет Wi-Fi,',
          isOccupied: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          number: '212',
          category: 'Двухместный',
          floor: '3',
          price: 200,
          isClean: true,
          comment: 'В ванной комнате: душевая зона с перегородкой из закалённого стекла. Халаты в номере',
          isOccupied: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          number: '213',
          category: 'Двухместный',
          floor: '4',
          price: 200,
          isClean: true,
          comment: 'Большая кровать, ванная комната с душевой кабиной, рабочее место(стол), звуконепроницаемые окна, WLAN интернет, телефон, телевизор с полоским экраном, DVD плеер, кондиционер, мини бар',
          isOccupied: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          number: '214',
          category: 'Двухместный',
          floor: '5',
          price: 200,
          isClean: true,
          comment: 'Прекрасный вид из окна',
          isOccupied: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          number: '300',
          category: 'Люкс',
          floor: '1',
          price: 300,
          isClean: true,
          comment: 'Посольский люкс',
          isOccupied: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          number: '301',
          category: 'Люкс',
          floor: '2',
          price: 300,
          isClean: true,
          comment: 'Джакузи, два туалета',
          isOccupied: false,

          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          number: '302',
          category: 'Люкс',
          floor: '3',
          price: 300,
          isClean: true,
          comment: 'Улучшенный номер, который отличается метражом',
          isOccupied: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          number: '303',
          category: 'Люкс',
          floor: '4',
          price: 300,
          isClean: true,
          comment: 'Обставлен более изысканной мебелью и современной техникой',
          isOccupied: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          number: '304',
          category: 'Люкс',
          floor: '5',
          price: 300,
          isClean: true,
          comment: 'Прекрасный вид из окна для состоятельных гостей',
          isOccupied: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          number: '305',
          category: 'Люкс',
          floor: '1',
          price: 300,
          isClean: true,
          comment: 'Посольский люкс',
          isOccupied: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          number: '306',
          category: 'Люкс',
          floor: '2',
          price: 300,
          isClean: true,
          comment: 'Джакузи, два туалета',
          isOccupied: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          number: '307',
          category: 'Люкс',
          floor: '3',
          price: 300,
          isClean: true,
          comment: 'Улучшенный номер, который отличается метражом',
          isOccupied: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          number: '308',
          category: 'Люкс',
          floor: '4',
          price: 300,
          isClean: true,
          comment: 'Обставлен более изысканной мебелью и современной техникой',
          isOccupied: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          number: '309',
          category: 'Люкс',
          floor: '5',
          price: 300,
          isClean: true,
          comment: 'Прекрасный вид из окна для состоятельных гостей',
          isOccupied: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          number: '310',
          category: 'Люкс',
          floor: '1',
          price: 300,
          isClean: true,
          comment: 'Посольский люкс',
          isOccupied: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          number: '311',
          category: 'Люкс',
          floor: '2',
          price: 300,
          isClean: true,
          comment: 'Джакузи, два туалета',
          isOccupied: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          number: '312',
          category: 'Люкс',
          floor: '3',
          price: 300,
          isClean: true,
          comment: 'Улучшенный номер, который отличается метражом',
          isOccupied: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          number: '313',
          category: 'Люкс',
          floor: '4',
          price: 300,
          isClean: true,
          comment: 'Обставлен более изысканной мебелью и современной техникой',
          isOccupied: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          number: '314',
          category: 'Люкс',
          floor: '5',
          price: 300,
          isClean: true,
          comment: 'Прекрасный вид из окна для состоятельных гостей',
          isOccupied: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      {},
    );
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete('Rooms', null, {});
  },
};
