// User
export const SET_AUTH = 'SET_AUTH';
export const LOGOUT = 'LOGOUT';

// Guest
export const SET_GUEST = 'SET_GUEST';
export const CURRENT_GUESTS = 'CURRENT_GUESTS';
export const ADD_GUEST = 'ADD_GUEST';
export const CLEAR_GUESTS = 'CLEAR_GUESTS';
export const EDIT_GUEST = 'EDIT_GUEST';

// Room
export const SET_ROOM = 'SET_ROOM';
export const READY_ROOM = 'READY_ROOM';
export const CATEGORY_ROOM = 'CATEGORY_ROOM';
export const NOT_READY_ROOM = 'NOT_READY_ROOM';
export const READY_ROOM_BY_CATEGORY = 'READY_ROOM_BY_CATEGORY';
export const GET_ROOMS = 'GET_ROOMS';
export const SORTED_ROOMS = 'SORTED_ROOMS';
export const READY_ROOMS_FOR_CHECKIN = 'READY_ROOMS_FOR_CHECKIN';

// reservation
export const SET_RESERVATION = 'SET_RESERVATION';
export const SET_TODAY_RESERVATION = 'SET_TODAY_RESERVATION';
export const SET_DATE_RESERVATION = 'SET_DATE_RESERVATION';
export const ADD_RESERVATION = 'ADD_RESERVATION';
export const REMOVE_RESERVATION = 'REMOVE_RESERVATION';
export const CHECKIN_RESERVATION = 'CHECKIN_RESERVATION';
export const ACTIVE_RESERVATION = 'ACTIVE_RESERVATION';
export const PAST_RESERVATION = 'PAST_RESERVATION';
export const CLOSE_RESERVATION = 'CLOSE_RESERVATION';
